/*
** primes.h for RSA in /home/ksa28/Kent/RSA/include
** 
** Made by Kevin Almansa
** Login   <ksa28>
** 
** Started on  Mon Jan 18 18:52:08 2016 Kevin Almansa
** Last update Mon Jan 18 18:52:10 2016 Kevin Almansa
*/

#ifndef __MATH_PRIMES__
# define __MATH_PRIMES__

typedef struct  s_primes {
  long		limit_used;
  long		length;
  long		*primes;
} t_primes;

/**
   Global Variable
   Set in primes.c

   All variables in struct set to 0 by default

   Used to contain a list of prime numbers generated by Sieve of Eratosthenes
**/
extern t_primes	g_prime_list;

/**
  Greatest Common Denominator: largest number that can devide two numbers
**/
long		gcd(long a, long b);

/**
  Simple memory effecient way to determine if a number is prime
**/
char		is_prime(long number);

/**
   Implementation of Sieve of Eratosthenes
   Will populate the global variable g_prime_list with an array of prime numbers
   up to limit, the limit used, and the number of primes found (length)
**/
void		sieve_of_eratosthenes(long limit);

#endif
